pipeline {
    agent any

    stages {

        stage('Install') {
            steps {
                dir('devops-project') {
                    sh 'docker run --rm -v $PWD:/app -w /app node:18 npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('devops-project') {
                    sh 'docker run --rm -v $PWD:/app -w /app node:18 npm test'
                }
            }
        }

        stage('Build Docker') {
            steps {
                dir('devops-project') {
                    sh 'docker build -t devops-app .'
                }
            }
        }

        stage('Run Docker') {
            steps {
                sh '''
                docker stop devops-app || true
                docker rm devops-app || true
                docker run -d -p 3000:3000 --name devops-app devops-app
                '''
            }
        }
    }
}
